"""S3-backed storage for per-user openclaw.json configs.

Each user's openclaw.json is stored at:
    s3://{bucket}/users/{user_id}/openclaw.json

This module handles CRUD for that config blob. The config dict itself
is generated by write_openclaw_config() in core/containers/config.py;
ConfigStore only serialises, stores, and retrieves the dict.
"""

import json
import logging

import boto3
from botocore.exceptions import ClientError

from core.config import settings

logger = logging.getLogger(__name__)


class ConfigStoreError(Exception):
    """Raised when S3 config operations fail."""

    def __init__(self, message: str, user_id: str = ""):
        super().__init__(message)
        self.user_id = user_id


class ConfigStore:
    """S3-backed storage for per-user openclaw.json configs."""

    def __init__(self, bucket: str):
        self._bucket = bucket
        self._s3 = boto3.client("s3", region_name=settings.AWS_REGION)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _s3_key(self, user_id: str) -> str:
        """Return the S3 object key for a user's config."""
        return f"users/{user_id}/openclaw.json"

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def get_config(self, user_id: str) -> dict | None:
        """Read openclaw.json from S3.

        Returns:
            Parsed config dict, or None if the key does not exist.

        Raises:
            ConfigStoreError: On S3 errors other than NoSuchKey, or
                on JSON parse failures.
        """
        key = self._s3_key(user_id)
        try:
            resp = self._s3.get_object(Bucket=self._bucket, Key=key)
            body = resp["Body"].read()
        except ClientError as exc:
            if exc.response["Error"]["Code"] == "NoSuchKey":
                return None
            raise ConfigStoreError(
                f"Failed to read config for {user_id}: {exc}",
                user_id=user_id,
            ) from exc

        try:
            return json.loads(body)
        except (json.JSONDecodeError, ValueError) as exc:
            raise ConfigStoreError(
                f"Failed to parse config for {user_id}: {exc}",
                user_id=user_id,
            ) from exc

    def put_config(self, user_id: str, config: dict) -> None:
        """Write openclaw.json to S3.

        Raises:
            ConfigStoreError: On S3 write failures.
        """
        key = self._s3_key(user_id)
        try:
            self._s3.put_object(
                Bucket=self._bucket,
                Key=key,
                Body=json.dumps(config, indent=2),
                ContentType="application/json",
            )
        except ClientError as exc:
            raise ConfigStoreError(
                f"Failed to write config for {user_id}: {exc}",
                user_id=user_id,
            ) from exc

    def delete_config(self, user_id: str) -> None:
        """Delete openclaw.json from S3.

        Idempotent: does not raise if the key is already absent
        (S3 delete_object is naturally idempotent).

        Raises:
            ConfigStoreError: On S3 errors.
        """
        key = self._s3_key(user_id)
        try:
            self._s3.delete_object(Bucket=self._bucket, Key=key)
        except ClientError as exc:
            raise ConfigStoreError(
                f"Failed to delete config for {user_id}: {exc}",
                user_id=user_id,
            ) from exc

    def config_exists(self, user_id: str) -> bool:
        """Check whether an openclaw.json exists in S3.

        Returns:
            True if the key exists, False otherwise.

        Raises:
            ConfigStoreError: On S3 errors other than 404.
        """
        key = self._s3_key(user_id)
        try:
            self._s3.head_object(Bucket=self._bucket, Key=key)
            return True
        except ClientError as exc:
            code = exc.response["Error"]["Code"]
            if code in ("404", "NoSuchKey"):
                return False
            raise ConfigStoreError(
                f"Failed to check config for {user_id}: {exc}",
                user_id=user_id,
            ) from exc
