// GooseTown agents are dynamically registered via the OpenClaw skill.
// Sprites are generated by PixelLab and served from S3/CloudFront.
// This file is kept for backward compatibility with any imports.

export const Descriptions: Array<{
  name: string;
  character: string;
  identity: string;
  plan: string;
}> = [];

export const characters: Array<{
  name: string;
  textureUrl: string;
  speed: number;
}> = [];

export const movementSpeed = 0.75;
